name: new_streamline
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.0
  pin_code_fields: ^8.0.1
  delayed_display: ^2.0.0
  lottie: ^3.1.0
  flash: ^3.1.0
  flutter_screenutil: ^5.9.0
  device_preview: ^1.1.0
  pinput: ^4.0.0
  provider: ^6.1.2
  get_it: ^7.6.4
  dartz: ^0.10.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_package_manager:
    git:
      url: https://github.com/mosabghorab/flutter_package_manager.git

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/vectors/
    - assets/animations/

  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
